version: '3'
services:
  scheduler:
    image: ghcr.io/buildbarn/bb-scheduler:20240716T044555Z-9850e82
    command:
    - /config/scheduler.jsonnet
    expose:
    - 8982
    - 8983
    - 8984
    - 9980
    ports:
    - 7982:7982
    - 8983:8983
    - 8984:8984
    volumes:
    - ./config:/config

  browser:
    image: ghcr.io/buildbarn/bb-browser:20240613T055327Z-f0fbe96
    command:
    - /config/browser.jsonnet
    expose:
    - 9980
    ports:
    - 7984:7984
    volumes:
    - ./config:/config

  runner-installer:
    image: ghcr.io/buildbarn/bb-runner-installer:20240716T044555Z-9850e82
    volumes:
    - ./volumes/bb:/bb

  # For situations where the more efficient FUSE worker is not supported,
  # the classic hardlinking example is shown here.
  worker-hardlinking-ubuntu22-04:
    image: ghcr.io/buildbarn/bb-worker:20240716T044555Z-9850e82
    command:
    - /config/worker-hardlinking-ubuntu22-04.jsonnet
    volumes:
    - ./config:/config
    - ./volumes/worker-hardlinking-ubuntu22-04:/worker

  runner-hardlinking-ubuntu22-04:
    image: ghcr.io/catthehacker/ubuntu:act-22.04@sha256:5f9c35c25db1d51a8ddaae5c0ba8d3c163c5e9a4a6cc97acd409ac7eae239448
    command:
    - sh
    - -c
    - while ! test -f /bb/installed; do sleep 1; done; exec /bb/tini -v -- /bb/bb_runner /config/runner-ubuntu22-04.jsonnet
    volumes:
    - ./config:/config
    - ./volumes/bb:/bb
    - ./volumes/worker-hardlinking-ubuntu22-04:/worker
    depends_on:
    - runner-installer
